# Generated by Django 2.2 on 2023-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20231202_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='SN',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topteacher',
            name='SN',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
