# Generated by Django 2.2 on 2023-11-30 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student_Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='None', max_length=200)),
                ('LastName', models.CharField(blank=True, default='None', max_length=200)),
                ('Phone_number', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('teachers_id', models.CharField(blank=True, max_length=200)),
                ('Role', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Formteacher', 'Formteacher')], default='Teacher', max_length=200)),
                ('Headshot', models.ImageField(blank=True, upload_to='assets/TeachersProfileimages')),
                ('classFormed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Class')),
                ('classes_taught', models.ManyToManyField(related_name='assigned_classes', to='Student_Portal.Class')),
                ('subjects_taught', models.ManyToManyField(to='Student_Portal.Subject')),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teachers_Portal.Teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Students_Pin_and_ID')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
