# Generated by Django 2.2 on 2023-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='SchoolSection',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('ClassTeacher', 'ClassTeacher')], default='Teacher', max_length=200),
        ),
    ]
