# Generated by Django 2.2 on 2023-12-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_Portal', '0002_auto_20231201_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Signature',
            field=models.ImageField(blank=True, upload_to='assets/TeachersSignatureimages'),
        ),
    ]
