# Generated by Django 2.2 on 2024-08-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_Portal', '0004_auto_20231202_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('ClassTeacher', 'ClassTeacher'), ('Admin', 'Admin')], default='Teacher', max_length=200),
        ),
    ]
