# Generated by Django 2.2 on 2023-11-30 08:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Excelfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Excel', models.FileField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjectallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Class')),
                ('subjects', models.ManyToManyField(to='Student_Portal.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Pin_and_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(blank=True, max_length=100, null=True)),
                ('student_Photo', models.ImageField(blank=True, null=True, upload_to='assets/Students')),
                ('student_name', models.CharField(blank=True, default='No name', max_length=100, null=True)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Sex', models.CharField(blank=True, max_length=100, null=True)),
                ('student_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('student_password', models.CharField(blank=True, default='No password', max_length=100, null=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalScore', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Totalnumber', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Average', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Position', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Remark', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('AcademicSession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.AcademicSession')),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Students_Pin_and_ID')),
                ('Term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Term')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstTest', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('FirstAss', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('MidTermTest', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('SecondAss', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('SecondTest', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('CA', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Exam', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Total', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Grade', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('SubjectPosition', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Remark', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Students_Pin_and_ID')),
                ('student_class', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Class')),
                ('students_result_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Student_Result_Data')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to='media')),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Student_Portal.Class')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalScore', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Totalnumber', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Average', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Position', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('AcademicSession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.AcademicSession')),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Students_Pin_and_ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstTermTotal', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('SecondTermTotal', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('ThirdTermTotal', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Total', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Average', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Grade', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('SubjectPosition', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Remark', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.Subject')),
                ('students_result_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.AnnualStudent')),
            ],
        ),
    ]
