# Generated by Django 2.2 on 2023-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
