# Generated by Django 2.2 on 2023-12-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0003_auto_20231201_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primaryresult',
            old_name='FirstTest',
            new_name='ResumptionTest',
        ),
        migrations.RenameField(
            model_name='primaryresult',
            old_name='SecondTest',
            new_name='Test',
        ),
    ]
