# Generated by Django 2.2 on 2023-12-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20231202_1920'),
        ('Student_Portal', '0007_auto_20231202_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.schoolSection'),
        ),
    ]
