# Generated by Django 2.2 on 2023-12-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0008_class_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryresult',
            name='FirstTermTotal',
        ),
        migrations.RemoveField(
            model_name='primaryresult',
            name='Total_200',
        ),
    ]
