# Generated by Django 2.2 on 2023-12-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0010_result_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryresult',
            name='ResumptionTest',
        ),
    ]
