# Generated by Django 2.2 on 2023-12-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0011_remove_primaryresult_resumptiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Class_signature',
            field=models.ImageField(blank=True, upload_to='assets/FormTeachersSignature'),
        ),
    ]
