# Generated by Django 2.2 on 2024-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0012_class_class_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualstudent',
            old_name='AcademicSession',
            new_name='academicsession',
        ),
        migrations.AddField(
            model_name='annualresult',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
