# Generated by Django 2.2 on 2024-08-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0013_auto_20240801_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualstudent',
            name='Remark',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='Verdict',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primaryresult',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_result_data',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
