# Generated by Django 2.2 on 2024-08-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0014_auto_20240806_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualresult',
            old_name='students_result_data',
            new_name='Student_name',
        ),
    ]
