# Generated by Django 2.2 on 2025-11-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0016_regenerate_student_pins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_pin_and_id',
            name='student_class',
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Student_Portal.AcademicSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Student_Portal.Students_Pin_and_ID')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='Student_Portal.Class')),
            ],
            options={
                'ordering': ['-academic_session__session', 'student__student_name'],
                'unique_together': {('student', 'academic_session')},
            },
        ),
    ]
